### PR TITLE
WIP: Document REST API using swagger spec.

### PR DESCRIPTION
**Pull request by danielballan**
This is not close to done, but it's a start. View using http://editor.swagger.io/

### CODE REVIEW

**Comment by danielballan** [comment]
Based on discussion in:

* https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/15
* #32 

It would be nice to get this done _before_ the sprint, but it's also somewhat sprint-friendly for someone who has experience with schemas like this.

**Comment by Mr0grog** [comment]
Paging @patcon: you said you were going to work on this a couple weeks back. Did you ever get anything done on this? Interested in collaborating with @danielballan?

**Comment by danielballan** [comment]
Thanks for the connection, @mr0grog. I pushed this early (half done) because you had mentioned meaning to document this on the front page.

**Comment by dcwalk** [comment]
Looping @titaniumbones and @patcon in explicitly because we talked a bit about this prep on Friday in terms of Toronto sprint prep :)

**Comment by mhucka** [comment]
This is a great idea! This is just a suggestion, but in addition to the API spec, having some examples of its use would be useful would be great. (Not sure where that would go – maybe there's already a document started somewhere?)

**Comment by dcwalk** [comment]
Also pointing @titaniumbones and @shaqsingh at this thread as we were talking about documenting the API in advance of Mozilla Global Sprint if possible 🎉

**Comment by danielballan** [comment]
I'll keep throwing commits at this branch today but collabators are welcome!

**Comment by Mr0grog** [comment]
@danielballan Do you want to get this merged now-ish and then keep working on it? (I haven’t yet reviewed in detail, but if so, I will ASAP.)

@mhucka Not documented anywhere yet. If there’s a way to put in Swagger, 👍, but I was also thinking of making each API path optionally have a `.html` at the end, and, in that case, returning a page with rendered output and a description, so you could actually point your browser at:

    http://web-monitoring-db.herokuapp.com/api/v0/pages?url=*.nasa.gov*

And get a little description of your query & other options at the top, then output below. Maybe overkill, though?

**Comment by b5** [comment]
Just a quick note, [spectacle](https://github.com/sourcey/spectacle) will do nice things in the way of generating examples.

**Comment by danielballan** [comment]
> Do you want to get this merged now-ish and then keep working on it? 

Either way. I would lean toward continuing work on this branch until it's closer to complete. I don't mind if others push to it.

**Comment by mhucka** [comment]
Ooooh, Swagger looks neat!

**Comment by Mr0grog** [comment]
Made a few minor additions to the docs. There’s more we could do, but this is a good start for people attending Mozilla Global Sprint.

NOTE: the Swagger file I’ve checked in here is invalid. Neither I nor @danielballan could figure out how to make the `..` in Change paths validate and I couldn’t figure out a way to describe optional path params in a valid way, either. It still renders fine and I think it’s worth prizing clear communication to readers to machine validity at this point. *(If anyone knows how to clean this up, that’d be awesome!)*

This also adds JS and CSS from [Swagger-UI](https://github.com/swagger-api/swagger-ui/) in order to render the API docs on the home page. (Check it out as soon as I’ve deployed at https://web-monitoring-db.herokuapp.com) Ideally, this would be static HTML, but this is at least a good start.

**Pull request merged**
