### PR TITLE
Add the dotenv gem

### PR DESCRIPTION
**Pull request by kholbekj**
As per #160 :)

### CODE REVIEW

**Comment by danielballan** [comment]
Great! Thanks for the contribution, @kholbekj. Would you like to add yourself to [the list of contributors in our README](https://github.com/edgi-govdata-archiving/web-monitoring-db#contributors)?

**Comment by kholbekj** [comment]
Sure!

**Comment by Mr0grog** [comment]
Hey, @kholbekj, are you planning to finish this?

**Comment by lightandluck** [comment]
@kholbekj Hope you don't mind, but this branch allowed edits, so I pushed the required changes rather than opening a new PR. Didn't want to lose the record of your work on this!

@Mr0grog I merged master, added `dotenv-rails` gem, and fixed a typo in `.env.example`. `dotenv-rails` installed `dotenv` as a dependency.

**Comment by kholbekj** [comment]
Sorry for not following up on this, of course great that you went ahead and fixed it.

**Comment by lightandluck** [comment]
Glad to know. Thanks so much for your help!

**Comment by Mr0grog** [comment]
Thanks both to @kholbekj and @lightandluck for adding this!

**Pull request merged**
