### PR TITLE
Update gemfile to include dotenv

### PR DESCRIPTION
**Pull request by accua**

### CODE REVIEW

**Comment by danielballan** [comment]
Thanks for the contribution, @accua. I think this requires some other coordinated changes and was accidentally superceded by #163.

**Comment by accua** [comment]
@danielballan Ah, no worries. Is there anything else that you guys need that is somewhat beginner friendly?

**Comment by danielballan** [comment]
Yes, check out the 'help wanted' label. Anything not "assigned" to a specific user should be up for grabs. Thanks again! https://github.com/edgi-govdata-archiving/web-monitoring-db/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted

**Comment by Mr0grog** [comment]
I’m going to close this one. Thanks again for the contribution, though, and definitely file PRs for other issues that you are interested in and are unassigned, @accua!

**Pull request closed without merging**
