### PR TITLE
Add EDGI S3 domains to ALLOWED_ARCHIVE_HOSTS.

### PR DESCRIPTION
**Pull request by danielballan**
At some point we discussed adding this to ``.env.example``. I don't think
we came to a clear conclusion, but it seems reasonable to me to add it.

### CODE REVIEW

**Comment by danielballan** [comment]
Nah, let's do it right.

**Comment by Mr0grog** [comment]
Well! I don’t know if auto-equating those would be “right.” In rebuttal to myself, not sure more code and special cases is better than a little more wordy basic configuration.

**Comment by danielballan** [comment]
Then I'm inclined to merge and revisit this after v0. Good enough?

**Comment by Mr0grog** [comment]
Agree! Sorry for muddying the waters a bit.

**Comment by danielballan** [comment]
:+1:

**Pull request merged**
