### PR TITLE
Add linting/style checking with Rubocop

### LINKED ISSUE #22: Add Code Style Checking
EDGI project guidelines [now include linting](https://github.com/edgi-govdata-archiving/overview/blob/master/protocol/linting.md), which is definitely something I should have set up here… a while ago. Probably easiest to start with [Rubocop](https://github.com/bbatsov/rubocop), though a service like [CodeClimate](https://codeclimate.com) could also be good.

See also https://github.com/bbatsov/ruby-style-guide and https://github.com/bbatsov/rails-style-guide

### PR DESCRIPTION
**Pull request by Mr0grog**
This fixes #22. I was hoping to set up Circle here, too (#23), but it looks like I don’t have the org rights necessary to turn it on, so will need help for that. (@danielballan? @titaniumbones?)

This is super messy because there are a lot of lint fixes. There are more that should be done, but I think this is enough for now (it’s a lot!). I/we can continue to clean things up as we work.

### CODE REVIEW

**Comment by titaniumbones** [comment]
Made you an owner. Here's pro dbly a smarter way to manage this question but on my phone in the Delhi airport after 36 hrs awake this is the best I can figure out.

**Comment by Mr0grog** [comment]
@titaniumbones No worries, thanks!

**Comment by Mr0grog** [comment]
And it passes tests on Circle!

**Comment by Mr0grog** [comment]
Since this doesn’t really make any meaningful changes to code that affect functionality, I’m going to go ahead and merge this.

**Comment by danielballan** [comment]
Hurray for automated tests!

**Pull request merged**
